export {
  addSession,
  areSessionsInitialized,
  getActiveSession,
  getActiveSessionId,
  getCurrentWindowLabel,
  getCurrentWindowName,
  getSessions,
  getWorkspaceSnapshot,
  initializeSessionsFromWorkspace,
  moveSession,
  persistWorkspace,
  removeSession,
  setActiveSession,
  setCurrentWindowName,
  setSessionAuxState,
  setSessionDirtyPaths,
  setSessionEditorRootDir,
  setSessionLocked,
  setSessionOpenEditorTabs,
  setSessionPinned,
  setSessionPtyId,
  setSessionResumeToken,
  setSessionTitle,
  setSessionViewMode,
  setSessionActiveEditorPath,
  syncSessionsFromWorkspace,
} from "../features/workspace/session-store.svelte";
